// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_unlockalien = "CgkIjbHGrKUJEAIQCA"; // <GPGSID>
        public const string achievement_drink_250 = "CgkIjbHGrKUJEAIQDA"; // <GPGSID>
        public const string achievement_666 = "CgkIjbHGrKUJEAIQDQ"; // <GPGSID>
        public const string achievement_kill_all_bosses = "CgkIjbHGrKUJEAIQDg"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIjbHGrKUJEAIQBA"; // <GPGSID>
        public const string achievement_highscore_500 = "CgkIjbHGrKUJEAIQCg"; // <GPGSID>
        public const string achievement_drink_500 = "CgkIjbHGrKUJEAIQEQ"; // <GPGSID>
        public const string achievement_69 = "CgkIjbHGrKUJEAIQEA"; // <GPGSID>
        public const string achievement_1000kill = "CgkIjbHGrKUJEAIQDw"; // <GPGSID>
        public const string achievement_classic = "CgkIjbHGrKUJEAIQBw"; // <GPGSID>
        public const string achievement_highscore_250 = "CgkIjbHGrKUJEAIQCQ"; // <GPGSID>
        public const string leaderboard_drink_score = "CgkIjbHGrKUJEAIQBQ"; // <GPGSID>
        public const string leaderboard_kill_score = "CgkIjbHGrKUJEAIQBg"; // <GPGSID>
        public const string achievement_highscore_1000 = "CgkIjbHGrKUJEAIQCw"; // <GPGSID>

}

